language: csharp
mono: 
  - latest
sudo: required
dotnet: 2.1
node_js:
  - "8.9.1"
script:
  - npm install yarn -g
  - bash build.sh Docker
deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master